file=open("Milan.txt","w")
file.write("This is file managament")
file.close()
print("File written successfully")
print("******************************")
file=open("Milan.txt","r")
print(file.read())
file.close()
print("******************************")
file=open("Milan.text","a")
file.write("\n This file is now appended")
file.close()
print("******************************")
file=open("Milan.txt","w+")
file.write("This is w+ mode using python")
print("File data : ",file.read())
